Repository nextcloud/files_fulltextsearch, pull requests merged in 2022-09, with the labels that each got.

#192 do not set indexOptions as array
  lib/Provider/FilesProvider.php
Labels: 3. to review

#191 ignore faulty FilesDocument
  lib/Service/ExtensionService.php
Labels: 3. to review, backport-request

#188 get userId from session
  lib/Service/SearchService.php
Labels: backport-request

#200 Create command-rebase.yml
  .github/workflows/command-rebase.yml
Labels: 3. to review
