Repository nextcloud/files_fulltextsearch, pull requests merged in 2025-02, with the labels that each got.

#295 fix: Throw if user does not exist
  lib/Service/FilesService.php
Labels: bug, 3. to review, backport-request

#291 set documentaccess on remove
  lib/Service/FilesService.php
Labels: backport-request

#290 cleaning code
  lib/Listeners/ListenersCore.php
  lib/Provider/FilesProvider.php
  lib/Service/ExternalFilesService.php
  lib/Service/FilesService.php
Labels: backport-request

#300 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#296 chore: Lint on PHP supported versions
  .github/workflows/lint-php.yml
Labels: 3. to review
